name: Test
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Script
        uses: actions/script@v3
        id: title
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context.payload.pull_request)
            return context.payload.pull_request.title
      - name: Output
        id: test
        run: echo "::set-output name::result=12345"
      - name: Echo
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: console.log(${{steps.test.outputs.result}})
      - name: Run
        uses: iwata-n/actions-python-template@main
        with:
          param: 'parameter'
